# Sonr Build Pipeline
#
#

# -- Pre Release Hooks --
before:
  hooks:
    - go mod download

# -- Individual Builds --
builds:
  # Highway CLI for macOS
  - id: "highway-cli-darwin"
    binary: highway-cli
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
    - amd64
    - arm64

  # Highway CLI for Linux
  - id: "highway-cli-linux"
    binary: highway-cli
    env:
      - CGO_ENABLED=0
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64


  # Highway CLI for Windows
  - id: "highway-cli-windows"
    binary: highway-cli
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe


# -- Artifacts from the build --
archives:
# Templating for CLI
- id: "highway-cli-archive"
  name_template: 'highway-cli-{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macos
    windows: win
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  builds:
  - highway-cli-darwin
  - highway-cli-linux
  - highway-cli-windows

# -- Checksums for the archives --
checksum:
  name_template: 'checksums.txt'

# -- Changelog Configuration --
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# -- Snapshot of the current version --
snapshot:
  name_template: "{{ .Tag }}-next"

# -- Release settings --
release:
  github:
    owner: sonr-io
    name: sonr
  prerelease: auto
  discussion_category_name: General
  mode: append
  extra_files:
    - name_template: CHANGELOG.md
    - name_template: LICENSE
    - name_template: README.md
  # Header template for the release body.
  # Defaults to empty.
  header: |
    #### Release {{ .Tag }} - {{ .Date }}

    Welcome to the new {{ .Tag }} Sonr Highway release. This release includes the following changes:


  # Footer template for the release body.
  # Defaults to empty.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}! With much love from the [Sonr Team](https://sonr.io).

    #### Connect with us
    - [Discord](https://discord.gg/HSTPCzDUsW)
    - [Twitter](https://twitter.com/sonr_io)
    - [Documentation](https://docs.sonr.io)
