# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Speedway < Formula
  desc ""
  homepage ""
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonr-io/speedway/releases/download/1.0.3/speedway_1.0.3_darwin_arm64.tar.gz"
      sha256 "88f45f67369c06f8a81719f2c3ed1d2cca48dd53b93b35b2ab11bc9559610ae3"

      def install
        bin.install "speedway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/speedway/releases/download/1.0.3/speedway_1.0.3_darwin_amd64.tar.gz"
      sha256 "d405139f32371c33700a39e31f4add55948a937175503ea6c20d2ae1ade8db68"

      def install
        bin.install "speedway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonr-io/speedway/releases/download/1.0.3/speedway_1.0.3_linux_arm64.tar.gz"
      sha256 "5bec7c8815903acc8bb0f1aa3d1e61dd976b8edd759567a95d71ef419c709893"

      def install
        bin.install "speedway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/speedway/releases/download/1.0.3/speedway_1.0.3_linux_amd64.tar.gz"
      sha256 "e23ea9eae63ac6326179c2e3566bcd75d36cb5afa83206f952e4ab9419744987"

      def install
        bin.install "speedway"
      end
    end
  end
end
