version: "3"
vars:
  VERSION: v0.0.1-test
tasks:
  swag:build:
    cmds:
      - swag init --parseDependency --parseInternal -g server/routes/server.go -o docs/ -ot yaml

  server:start:debug:
    dir: server
    cmds:
      - go run main.go
    env:
      GIN_MODE: "debug"
      RPDisplayName: "Sonr - Speedway"
      RPID: "localhost"
      RPOrigin: "http://0.0.0.0:4040"
      Address: "0.0.0.0:4040"
      StaticDir: "./build"
      SONR_RPC_ADDR_PUBLIC: 137.184.190.146:9090

  server:start:release:
    dir: server
    cmds:
      - go run main.go
    env:
      GIN_MODE: "release"
      RPDisplayName: "Sonr - Speedway"
      RPID: "localhost"
      RPOrigin: "http://0.0.0.0:4040"
      Address: "0.0.0.0:4040"
      StaticDir: "./build"
      SONR_RPC_ADDR_PUBLIC: 137.184.190.146:9090
