version: "3"
vars:
  VERSION: v0.0.1-test
tasks:
  swag:build:
    cmds:
      - swag init --generalInfo server/routes/server.go -o docs/ -pd
  build:ui:prod:
    cmds:
      - npm install
      - npm run build:embed
  build:ui:dev:
    cmds:
      - npm install
      - npm run build:debug
  build:cmd:
    cmds:
      - npm install
      - npm run build:embed
      - go build -o bin/speedway
      - mv bin/speedway /usr/local/bin/
