export const ROUTE_LOGIN = "/"
export const ROUTE_SIGNUP = "/signup"
export const ROUTE_DASHBOARD = "/dashboard"
export const ROUTE_SCHEMAS = "/schema"
export const ROUTE_OBJECTS = "/objects"
export const ROUTE_BUCKETS = "/buckets"
export const ROUTE_ACCESS_API = "/access-api"
export const ROUTE_DID_UTILITY = "/did-utility"
export const ROUTE_DOCS_AND_SUPPORT = "/docs-and-support"
export const ROUTE_BLOCK_EXPLORER = "/block-explorer"
export const ROUTE_404 = "/404"

// app modal context
export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT"
export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
export const MODAL_CONTENT_NEW_SCHEMA = "MODAL_CONTENT_NEW_SCHEMA"
export const MODAL_CONTENT_NEW_OBJECT = "MODAL_CONTENT_NEW_OBJECT"
