basePath: /api/v1
definitions:
  apiv1.CreateSchemaResponse:
    properties:
      what_is:
        items:
          type: integer
        type: array
    type: object
  apiv1.LoginResponse:
    properties:
      success:
        type: boolean
    type: object
  object.ObjectReference:
    properties:
      cid:
        type: string
      did:
        type: string
      label:
        type: string
    type: object
  types.SchemaDefinition:
    properties:
      creator:
        description: |-
          Represents the types of fields a schema can have
          the DID for this schema
        type: string
      fields:
        description: the properties of this schema
        items:
          $ref: '#/definitions/types.SchemaKindDefinition'
        type: array
      label:
        description: an alternative reference point
        type: string
    type: object
  types.SchemaKindDefinition:
    properties:
      field:
        description: Type of a single schema property
        type: integer
      link:
        type: string
      link_kind:
        description: Optional field for a link context if `SchemaKind` is of type
          `Link`
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: team@sonr.io
    name: API Support
    url: https://sonr.io/
  description: Create accounts, schemas, buckets and objects in a scalable way utilizing
    the Sonr architecture.
  license:
    name: OpenGLv3
  termsOfService: https://sonr.io/terms
  title: Speedway API
  version: "2.0"
paths:
  /account/create:
    post:
      description: Create a new account on Sonr using the Registry module of Sonr's
        Blockchain.
      parameters:
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Address
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: CreateAccount
      tags:
      - account
  /account/login:
    post:
      description: Login to an existing account on Sonr using the Registry module
        of Sonr's Blockchain.
      parameters:
      - description: Did
        example: '"snr172ljvam8m7xxlv59v6w27lula58zwwct3vgn9p"'
        in: body
        name: Did
        required: true
        schema:
          type: string
      - description: Password
        example: '"Password"'
        in: body
        name: Password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiv1.LoginResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: LoginAccount
      tags:
      - account
  /object/build:
    post:
      description: Build an object on Sonr using the object module of Sonr's Blockchain.
      parameters:
      - description: Address
        example: '"snr172ljvam8m7xxlv59v6w27lula58zwwct3vgn9p"'
        in: body
        name: Address
        required: true
        schema:
          type: string
      - description: SchemaDid
        example: '"did:sonr:172ljvam8m7xxlv59v6w27lula58zwwct3vgn9p"'
        in: body
        name: SchemaDid
        required: true
        schema:
          type: string
      - description: Label
        example: '"MyObject"'
        in: body
        name: Label
        required: true
        schema:
          type: string
      - description: Object
        in: body
        name: Object
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/object.ObjectReference'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: BuildObject
      tags:
      - object
  /object/get:
    post:
      description: Get an object on Sonr using the object module of Sonr's Blockchain.
      parameters:
      - description: Address
        example: '"snr172ljvam8m7xxlv59v6w27lula58zwwct3vgn9p"'
        in: body
        name: Address
        required: true
        schema:
          type: string
      - description: SchemaDid
        example: '"did:sonr:172ljvam8m7xxlv59v6w27lula58zwwct3vgn9p"'
        in: body
        name: SchemaDid
        required: true
        schema:
          type: string
      - description: ObjectCid
        example: '"bafyreigfzxrtvfzuaoyhn5vgndneeeirq62efgf2s3igmoenxgx7jxy2cm"'
        in: body
        name: ObjectCid
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/object.ObjectReference'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetObject
      tags:
      - object
  /schema/create:
    post:
      description: Create a schema utilizing motor client. Returns the WhatIs of the
        schema created.
      parameters:
      - description: Address of the user
        in: query
        name: address
        required: true
        type: string
      - description: Label of the schema
        in: query
        name: label
        required: true
        type: string
      - description: Fields of the schema
        in: query
        name: fields
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiv1.CreateSchemaResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: CreateSchema
      tags:
      - schema
  /schema/get:
    post:
      description: Get a schema utilizing motor client. Returns the WhatIs of the
        schema that is retrieved.
      parameters:
      - description: Did
        in: query
        name: did
        required: true
        type: string
      - description: Creator
        in: query
        name: creator
        required: true
        type: string
      - description: Schema
        in: query
        name: schema
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SchemaDefinition'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetSchema
      tags:
      - schema
swagger: "2.0"
