name: Build-and-Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x]
        node-version: [16.x]
    steps:
      - name: Starting Build and Test
        run: go run main.go serve
      - name: Setup & Test
        uses: actions/checkout@v3
        working-directory: ./server-in-memory
        run: |
          npm install
          npm run smoke-detector