name: Build-and-Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - run: go run main.go serve
      # cd into the server directory
      - name: cd into server directory
        run: cd server-in-memory
      # use node version 16.x
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # run the install command
      - name: install dependencies
        run: npm install
      # run the test command
      - name: run tests
        run: npm run smoke-detector
      