name: Build-and-Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x]
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Taskfile
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
      - name: Run server
        run: |
          task server:start:debug
      # cd into the server directory
      - name: cd into server directory
        run: cd server-in-memory
      # use node version 16.x
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # run the install command
      - name: install dependencies
        run: npm install
      # run the test command
      - name: run tests
        run: npm run smoke-detector
      