name: Build-and-Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup & Test
        working-directory: ./server-in-memory
        run: |
          npm install
          npm run smoke-detector