name: Release Binaries

on:
  release:
    types: [ published ]

jobs:
  binary:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1    
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.working-directory }}
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token