name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.ACTIONS_GH_TOKEN }}
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}