name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install Cross Compiler for linux/arm64
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get -y install gcc-aarch64-linux-gnu
      - name: Run GoReleaser (Linux)
        if: matrix.os == 'ubuntu-22.04'
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --id linux-build
        env:
          RUNNER_ARCH: amd64
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GH_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Run GoReleaser (Darwin)
        if: matrix.os == 'macos-12'
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --id darwin-build
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GH_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}