name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --id darwin-build
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: goreleaser
          path: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GH_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}